### PR TITLE
fix: isOnMobile is iOS and *any* android.

### LINKED ISSUE #369: YouTube Pre-loader / Spinner issues on Mobiles
We're using videojs on a premium theme of ours for fullscreen video backgrounds and we're experiencing issues with YouTube videos being able to be played on mobile devices.

Our first issue encountered was that specifically on YouTube videos, when having the "big play button" enabled, it would not trigger the YouTube video to play when clicked. Though we managed to come up with a solution that worked by simply removing that button. It wasn't a pretty solution but it did the trick. (note: this is only applied on smaller devices)

Now our next issue is regarding when "autoplay" is enabled. We are very much aware of the fact autoplay will not work on mobile devices, but what it does instead is causes the "preloader / spinner" to constantly show as if it were trying to load the video. After awhile, it displays an error message about being unable to load the video.

Click outside the middle of the video (where the preloader / spinner is) will not play the video, but clicking outside of that (anywhere else on the browser) it will play the video. This is fine and dandy, but it's deceptive to visitors, thinking the video is trying to load but isn't, not knowing that they can click outside it.

This only happens when the "autoplay" is enabled.

Here are two examples we have that will demonstrate the issues faced:

Autoplay enabled: http://www.kingsizetheme.com/home/youtube-fullscreen-background/

Autoplay disabled: http://www.kingsizetheme.com/home/youtube-fullscreen-background-no-ap/

Is there a suggestion or solution already for resolving this issue?

If not, or hasn't yet been reported, do you have any suggestions?

Thanks for your time and insight!

Should also note out that this happens on all mobile devices and browsers tested thus far.

We are also using the latest version of video.js.

### PR DESCRIPTION
**Pull request by gkatsev**
Fixes #369.

### CODE REVIEW

File: src/Youtube.js [hunk 1]
```diff
@@ -638,7 +638,7 @@ THE SOFTWARE. */
     return (e === 'video/youtube');
   };
 
-  var _isOnMobile = videojs.browser.IS_IOS || useNativeControlsOnAndroid();
+  var _isOnMobile = videojs.browser.IS_IOS || videojs.browser.IS_ANDROID;
```
Comment (BrandonOCasey) [inline src/Youtube.js]: it may be a good idea to move this towards the top of the file where all the other scope level globals are. Seems weird to have this mid-file. LGTM other than that though.

Comment (gkatsev) [inline src/Youtube.js]: makes sense
